In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_2018 = pd.read_csv("./survey_results_public_2018.csv")

/Users/owenbchiu/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
for i in raw_2018.columns:
    print(i)

Respondent
Hobby
OpenSource
Country
Student
Employment
FormalEducation
UndergradMajor
CompanySize
DevType
YearsCoding
YearsCodingProf
JobSatisfaction
CareerSatisfaction
HopeFiveYears
JobSearchStatus
LastNewJob
AssessJob1
AssessJob2
AssessJob3
AssessJob4
AssessJob5
AssessJob6
AssessJob7
AssessJob8
AssessJob9
AssessJob10
AssessBenefits1
AssessBenefits2
AssessBenefits3
AssessBenefits4
AssessBenefits5
AssessBenefits6
AssessBenefits7
AssessBenefits8
AssessBenefits9
AssessBenefits10
AssessBenefits11
JobContactPriorities1
JobContactPriorities2
JobContactPriorities3
JobContactPriorities4
JobContactPriorities5
JobEmailPriorities1
JobEmailPriorities2
JobEmailPriorities3
JobEmailPriorities4
JobEmailPriorities5
JobEmailPriorities6
JobEmailPriorities7
UpdateCV
Currency
Salary
SalaryType
ConvertedSalary
CurrencySymbol
CommunicationTools
TimeFullyProductive
EducationTypes
SelfTaughtTypes
TimeAfterBootcamp
HackathonReasons
AgreeDisagree1
AgreeDisagree2
AgreeDisagree3
LanguageWorkedWith
LanguageDesireNextYear
DatabaseWorkedWith
DatabaseDesireNextYear
PlatformWorkedWith
PlatformDesireNextYear
FrameworkWorkedWith
FrameworkDesireNextYear
IDE
OperatingSystem
NumberMonitors
Methodology
VersionControl
CheckInCode
AdBlocker
AdBlockerDisable
AdBlockerReasons
AdsAgreeDisagree1
AdsAgreeDisagree2
AdsAgreeDisagree3
AdsActions
AdsPriorities1
AdsPriorities2
AdsPriorities3
AdsPriorities4
AdsPriorities5
AdsPriorities6
AdsPriorities7
AIDangerous
AIInteresting
AIResponsible
AIFuture
EthicsChoice
EthicsReport
EthicsResponsible
EthicalImplications
StackOverflowRecommend
StackOverflowVisit
StackOverflowHasAccount
StackOverflowParticipate
StackOverflowJobs
StackOverflowDevStory
StackOverflowJobsRecommend
StackOverflowConsiderMember
HypotheticalTools1
HypotheticalTools2
HypotheticalTools3
HypotheticalTools4
HypotheticalTools5
WakeTime
HoursComputer
HoursOutside
SkipMeals
ErgonomicDevices
Exercise
Gender
SexualOrientation
EducationParents
RaceEthnicity
Age
Dependents
MilitaryUS
SurveyTooLong
SurveyEasy

In [13]:
df_2018 = raw_2018[['Respondent', 'Country', 'FormalEducation', 'DevType', 'YearsCoding', 'ConvertedSalary', 'LanguageWorkedWith', 'DatabaseWorkedWith', 'PlatformWorkedWith', 'FrameworkWorkedWith']]

In [8]:
edu_map = pd.read_csv('edu_map.csv')

In [14]:
df_2018 = df_2018.merge(edu_map, left_on='FormalEducation', right_on='EdLevel', how='left').drop(['Unnamed: 0', 'EdLevel'], axis=1)

In [12]:
country_map = pd.read_csv('country_map.csv')

In [16]:
df_2018 = df_2018.merge(country_map, on='Country', how='left').drop(['Unnamed: 0'], axis=1)

In [17]:
df_2018['YearsCoding'].unique()

array(['3-5 years', '30 or more years', '24-26 years', '18-20 years',
       '6-8 years', '9-11 years', '0-2 years', '15-17 years',
       '12-14 years', '21-23 years', '27-29 years', nan], dtype=object)

In [18]:
df_2018.loc[df_2018['YearsCoding']=='3-5 years', 'YearsCode'] = 4
df_2018.loc[df_2018['YearsCoding']=='30 or more years', 'YearsCode'] = 30
df_2018.loc[df_2018['YearsCoding']=='24-26 years', 'YearsCode'] = 25
df_2018.loc[df_2018['YearsCoding']=='18-20 years', 'YearsCode'] = 19
df_2018.loc[df_2018['YearsCoding']=='6-8 years', 'YearsCode'] = 7
df_2018.loc[df_2018['YearsCoding']=='9-11 years', 'YearsCode'] = 10
df_2018.loc[df_2018['YearsCoding']=='0-2 years', 'YearsCode'] = 1
df_2018.loc[df_2018['YearsCoding']=='15-17 years', 'YearsCode'] = 16
df_2018.loc[df_2018['YearsCoding']=='12-14 years', 'YearsCode'] = 13
df_2018.loc[df_2018['YearsCoding']=='21-23 years', 'YearsCode'] = 22
df_2018.loc[df_2018['YearsCoding']=='27-29 years', 'YearsCode'] = 28
df_2018.loc[df_2018['YearsCoding']==np.nan, 'YearsCode'] = np.nan

In [28]:
df_2018[df_2018['YearsCode'].isna()]

Empty DataFrame
Columns: [Respondent, Country, FormalEducation, DevType, YearsCoding, ConvertedSalary, LanguageWorkedWith, DatabaseWorkedWith, PlatformWorkedWith, FrameworkWorkedWith, EducationAvgComp, CountryAvgComp, YearsCode]
Index: []

In [27]:
df_2018.loc[df_2018['YearsCode'].isna(), 'YearsCode'] = 10

In [30]:
df_2018['ConvertedSalary'] = df_2018['ConvertedSalary']*1.04622

In [32]:
df_2018 = df_2018.rename(columns={'ConvertedSalary': 'ConvertedComp'})

In [33]:
df_2018 = df_2018[~df_2018['ConvertedComp'].isna()]
df_2018 = df_2018[df_2018['ConvertedComp']<1000000]

In [35]:
temp1 = df_2018['DevType'].str.split(';', expand=True)

In [36]:
all_positions = []
for row in range(temp1.shape[0]):
    j = temp1.iloc[row].as_matrix()
    for position in j:
        if position not in all_positions:
            all_positions.append(position)

/Users/owenbchiu/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [37]:
all_positions.remove(None)

In [39]:
all_positions.pop(-1)

nan

In [41]:
all_positions.sort()

In [42]:
all_positions

['Back-end developer',
 'C-suite executive (CEO, CTO, etc.)',
 'Data or business analyst',
 'Data scientist or machine learning specialist',
 'Database administrator',
 'Designer',
 'Desktop or enterprise applications developer',
 'DevOps specialist',
 'Educator or academic researcher',
 'Embedded applications or devices developer',
 'Engineering manager',
 'Front-end developer',
 'Full-stack developer',
 'Game or graphics developer',
 'Marketing or sales professional',
 'Mobile developer',
 'Product manager',
 'QA or test developer',
 'Student',
 'System administrator']

In [43]:
for i in all_positions:
    df_2018[i] = 0

In [44]:
for i in range(temp1.shape[0]):
    j = list(temp1.iloc[i].as_matrix())
    for item in j:
        if type(item)==type('str'):
            df_2018.at[i, item] = 1

/Users/owenbchiu/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

In [46]:
df_2018[all_positions].head(20)

,Back-end developer,"C-suite executive (CEO, CTO, etc.)",Data or business analyst,Data scientist or machine learning specialist,Database administrator,Designer,Desktop or enterprise applications developer,DevOps specialist,Educator or academic researcher,Embedded applications or devices developer,Engineering manager,Front-end developer,Full-stack developer,Game or graphics developer,Marketing or sales professional,Mobile developer,Product manager,QA or test developer,Student,System administrator
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
33,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
35,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
42,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
changes = {'Educator or academic researcher': 'Academic researcher', 
'QA or test developer': 'Developer, QA or test',
'Back-end developer': 'Developer, back-end',
'Desktop or enterprise applications developer': 'Developer, desktop or enterprise applications',
'Embedded applications or devices developer': 'Developer, embedded applications or devices',
'Front-end developer': 'Developer, front-end', 
'Full-stack developer': 'Developer, full-stack',
'Game or graphics developer': 'Developer, game or graphics',
'Mobile developer': 'Developer, mobile',
}

In [48]:
df_2018 = df_2018.rename(columns=changes)

In [50]:
df_2018['Educator'] = 0 
df_2018['Engineer, data'] = 0
df_2018['Engineer, site reliability'] = 0
df_2018['Scientist'] = 0
df_2018['Senior executive/VP'] = 0

In [51]:
all_positions = ['Academic researcher',
 'Data or business analyst',
 'Data scientist or machine learning specialist',
 'Database administrator',
 'Designer',
 'DevOps specialist',
 'Developer, QA or test',
 'Developer, back-end',
 'Developer, desktop or enterprise applications',
 'Developer, embedded applications or devices',
 'Developer, front-end',
 'Developer, full-stack',
 'Developer, game or graphics',
 'Developer, mobile',
 'Educator',
 'Engineer, data',
 'Engineer, site reliability',
 'Engineering manager',
 'Marketing or sales professional',
 'Product manager',
 'Scientist',
 'Senior executive/VP',
 'Student',
 'System administrator']

In [53]:
df_2018[all_positions].columns

Index(['Academic researcher', 'Data or business analyst',
       'Data scientist or machine learning specialist',
       'Database administrator', 'Designer', 'DevOps specialist',
       'Developer, QA or test', 'Developer, back-end',
       'Developer, desktop or enterprise applications',
       'Developer, embedded applications or devices', 'Developer, front-end',
       'Developer, full-stack', 'Developer, game or graphics',
       'Developer, mobile', 'Educator', 'Engineer, data',
       'Engineer, site reliability', 'Engineering manager',
       'Marketing or sales professional', 'Product manager', 'Scientist',
       'Senior executive/VP', 'Student', 'System administrator'],
      dtype='object')